### ISSUE TITLE
Issue on running RefMon (Fabric Manager) from test-ms example /Multiswitch

### ISSUE THREAD

**Issue by pythonxian** [sdn-ixp/iSDX#7]
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ovs>=2.6.0

**Comment by Gaurav-Pande** [comment]
I am facing the same issue/error. Is there is a fix for this?

Thanks!
